### ISSUE TITLE
App does not take full screen

### ISSUE THREAD

**Issue by Thibaultce** [davidortinau/WeatherTwentyOne#19]
I cloned the repo then launch the application on multiple emulators (IPhone Pro 12, IPhone 12) and on my own device (IPhone 11 Pro) and the application does not render as in the screenshots.
The application does not take the full screen as the following pictures shows.

<img width="440" alt="Screenshot 2021-05-27 at 19 24 10" src="https://user-images.githubusercontent.com/9657189/119870372-97690400-bf21-11eb-8b44-c8c58eefa09d.png">

I'm on Mac and I'm using this command to launch the application:
```
dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=<UDID>
// My own device
dotnet build -t:Run -f net6.0-ios -r ios-arm64 -p:_DeviceName=<UDID>
```

**Comment by davidortinau** [comment]
Thanks for the report. Looks like it didn't generate the splash perhaps, and thus the app didn't know how to size. @Redth fyi.

@Thibaultce when you do a `dotnet clean` then `dotnet restore`, delete the bin/obj to force it to recreate the images, delete the app from your simulator, and then run again...does it still behave the same?

**Comment by Thibaultce** [comment]
After a clean and a restore, it works on both the emulator and the real device, thanks !
